package jp.andpad.api.domain;

public enum SaasModuleCode {
    DX, CRM, ATTENDANCE, ECONTRACT, CHATBOT, DOC_RAG, CONSTRUCTION_MGMT, DRAWINGS, BLACKBOARD, INSPECTION, PROJECT_BOARD, INQUIRY_PROFIT, ORDERS, REMOTE_SITE, DOC_APPROVAL, SCAN_3D, BILLING, WORK_RATE, SITE_ACCESS, E_DELIVERY, BM, ANALYTICS, API_INTEGRATION, BIM, BUDGET_MGMT
}
