package jp.andpad.api.domain;

public enum VideoCategory {
    ENDODONTICS, PERIODONTICS, PROSTHODONTICS, ORAL_SURGERY, IMPLANT, ORTHODONTICS, PEDIATRIC, RADIOLOGY, INFECTION_CONTROL, COMMUNICATION
}
